version: "3.8"

services: 
    server:
        build: 
            context: ./
            dockerfile: Dockerfile
        volumes: 
            - .:/app
            - ./node_modules:/app/node_modules
        ports: 
            - '3000:3000'

