export enum DevToolsAction {
  SET_SELECTOR = 'SET_SELECTOR',
  CLEAR_SELECTOR = 'CLEAR_SELECTOR'
}

export enum ProjectsAction {
  FETCH_PROJECTS = 'FETCH_PROJECTS',
  FETCH_PROJECT = 'FETCH_PROJECT',
  SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT',
  CLEAR_CURRENT_PROJECT = 'CLEAR_CURRENT_PROJECT'
}
